tasks:
  - name: Setup
    before: |
      curl -sfL gpm.simonemms.com | bash

      gpm install pre-commit

      gp sync-done setup

      pre-commit install --install-hooks -t pre-commit -t commit-msg

      gp sync-done pre-commit

      exit 0

  - name: App
    env:
      npm_config_yes: true
      NUXT_TELEMETRY_DISABLED: 1
    init: |
      yarn
    command: |
      gp sync-await setup

      yarn dev

ports:
  - port: 3000
    visibility: private

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - waderyan.gitblame
    - Vue.volar
    - Nuxt.mdc
